apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversaotemperaturadeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: evandronuss/conversao-temperatura:v1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - port: 3000
      protocol: TCP
      name: http
      targetPort: 8080
      nodePort: 30000
  type: NodePort
